# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 5.3.x

    - name: Calculate Version and Set .nuspec
      run: |
        chmod +x scripts/calculate-version.sh
        ./scripts/calculate-version.sh

    - name: Restore 
      run: dotnet restore
  
    - name: Build 
      run: dotnet build -c Release
    - name: Pack NuGet package
      run: nuget pack WeatherCapybara.nuspec
    - name: Publish to GitHub Packages
      run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/wiakut/index.json --api-key ${TOKEN}
      env:
        TOKEN: ${{ secrets.TOKEN }}
